### ISSUE TITLE
cattrs 1.1.1 and aws cdk

### ISSUE THREAD

**Issue by HerzogDoomEagle** [Tinche/cattrs#104]
_*** cattrs version: 1.1.1
* Python version: 3.6.9
* Operating System: Ubuntu**_

**### Description**

When attempting to perform AWS CDK functions (i.e. 'cdk ls', an error occurs with the new version of cattrs:
_______________________
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from aws_cdk import core
  File "/home/user/code/CDK-Infrastructure/.env/lib/python3.6/site-packages/aws_cdk/core/__init__.py", line 904, in <module>
    import jsii
  File "/home/user/code/CDK-Infrastructure/.env/lib/python3.6/site-packages/jsii/__init__.py", line 4, in <module>
    from ._runtime import (
  File "/home/user/code/CDK-Infrastructure/.env/lib/python3.6/site-packages/jsii/_runtime.py", line 10, in <module>
    from ._kernel import Kernel
  File "/home/user/code/CDK-Infrastructure/.env/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 15, in <module>
    from .providers import BaseProvider, ProcessProvider
  File "/home/user/code/CDK-Infrastructure/.env/lib/python3.6/site-packages/jsii/_kernel/providers/__init__.py", line 2, in <module>
    from .process import ProcessProvider
  File "/home/user/code/CDK-Infrastructure/.env/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 16, in <module>
    import cattr  # type: ignore
  File "/home/user/code/CDK-Infrastructure/.env/lib/python3.6/site-packages/cattr/__init__.py", line 1, in <module>
    from .converters import Converter, GenConverter, UnstructureStrategy
  File "/home/user/code/CDK-Infrastructure/.env/lib/python3.6/site-packages/cattr/converters.py", line 18, in <module>
    from ._compat import (
  File "/home/user/code/CDK-Infrastructure/.env/lib/python3.6/site-packages/cattr/_compat.py", line 31, in <module>
    from typing import get_args, get_origin  # NOQA
ImportError: cannot import name 'get_args'
Subprocess exited with error 1
_______________________

**### What I Did**
I attempted to use an old version of cattrs - 1.0.0 (since 1.1.0 was yanked).
This yields the following error:
_______________________
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from aws_cdk import core
  File "/home/user/code/CDK-Infrastructure/.env/lib/python3.6/site-packages/aws_cdk/core/__init__.py", line 904, in <module>
    import jsii
  File "/home/user/code/CDK-Infrastructure/.env/lib/python3.6/site-packages/jsii/__init__.py", line 4, in <module>
    from ._runtime import (
  File "/home/user/code/CDK-Infrastructure/.env/lib/python3.6/site-packages/jsii/_runtime.py", line 10, in <module>
    from ._kernel import Kernel
  File "/home/user/code/CDK-Infrastructure/.env/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 15, in <module>
    from .providers import BaseProvider, ProcessProvider
  File "/home/user/code/CDK-Infrastructure/.env/lib/python3.6/site-packages/jsii/_kernel/providers/__init__.py", line 2, in <module>
    from .process import ProcessProvider
  File "/home/user/code/CDK-Infrastructure/.env/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 16, in <module>
    import cattr  # type: ignore
ModuleNotFoundError: No module named 'cattr'
______________________
'cattr' has no installation candidate in pip.
______________________
I initially encountered this error using Python 3.6.9.

**Comment by Tinche** [comment]
Version 1.1.1 doesn't support 3.6, so you need to find a way to install 1.0.0 in the virtualenv you're using.

The PyPI package name is 'cattrs', this mirrors 'attrs'/`import attr`, so give installing that a shot.

**Comment by HerzogDoomEagle** [comment]
Thank you, resolved.
