### ISSUE TITLE
Test failing with Python 2.7

### ISSUE THREAD

**Issue by brouhaha** [Tinche/cattrs#39]
* cattrs version: 0.9.0
* Python version: 2.7.15, 3.6.5
* Operating System: Fedora 28

### Description

I packaged cattrs for Fedora a while back, using 0.6.0, and building for Python 2.7 and 3.6. Now I'm trying to update the package to 0.9.0 to support Python 3.7 for Fedora 29. However, even when building on Fedora 28 with Python 2.7.15 and 3.6.5, when running the tests py.test is giving me an error about an unexpected keyword suppress_health_checks.

### What I Did

command to start the build:
```
rpmbuild -ba python-cattrs.spec
```

excerpt of output:
```
+ py.test-2.7 -v
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/_pytest/config.py", line 366, in _importconftest
    mod = conftestpath.pyimport()
  File "/usr/lib/python2.7/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "/usr/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 213, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/usr/lib/python2.7/site-packages/py/_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "/home/eric/rpmbuild/BUILD/cattrs-0.9.0/tests/conftest.py", line 14, in <module>
    "tests", suppress_health_check=(HealthCheck.too_slow,)
TypeError: register_profile() got an unexpected keyword argument 'suppress_health_check'
ERROR: could not load /home/eric/rpmbuild/BUILD/cattrs-0.9.0/tests/conftest.py
```

**Comment by eric-appion** [comment]
Hypothesis 3.44.24 is the latest in Fedora 28. Hypothesis 3.66.11 will be in Fedora 29; I'll give it a try with that.
