### ISSUE TITLE
Python 3.6 Support

### ISSUE THREAD

**Issue by hawkowl** [Tinche/cattrs#4]
* cattrs version: 0.2.0
* Python version: 3.6.0
* Operating System: Linux x64

### Description

`cattrs` fails to import on Python 3.6. :(

```
2017-01-04T09:10:24.063036+00:00 app[web.1]: Traceback (most recent call last):
2017-01-04T09:10:24.063066+00:00 app[web.1]:   File "/app/.heroku/python/bin/twist", line 11, in <module>
2017-01-04T09:10:24.063243+00:00 app[web.1]:     load_entry_point('Twisted==16.6.0', 'console_scripts', 'twist')()
2017-01-04T09:10:24.063246+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/twisted/application/twist/_twist.py", line 132, in main
2017-01-04T09:10:24.063387+00:00 app[web.1]:     options = cls.options(argv)
2017-01-04T09:10:24.063398+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/twisted/application/twist/_twist.py", line 38, in options
2017-01-04T09:10:24.063570+00:00 app[web.1]:     options.parseOptions(argv[1:])
2017-01-04T09:10:24.063685+00:00 app[web.1]:     Options.parseOptions(self, options=options)
2017-01-04T09:10:24.063571+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/twisted/application/twist/_options.py", line 160, in parseOptions
2017-01-04T09:10:24.063687+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/twisted/python/usage.py", line 265, in parseOptions
2017-01-04T09:10:24.063866+00:00 app[web.1]:     self.subOptions = parser()
2017-01-04T09:10:24.063867+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/twisted/application/twist/_options.py", line 185, in <lambda>
2017-01-04T09:10:24.064000+00:00 app[web.1]:     lambda plugin=plugin: plugin.options(),
2017-01-04T09:10:24.064002+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/twisted/application/service.py", line 76, in get
2017-01-04T09:10:24.064110+00:00 app[web.1]:     return namedAny(self.module).Options
2017-01-04T09:10:24.064111+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/twisted/python/reflect.py", line 300, in namedAny
2017-01-04T09:10:24.064278+00:00 app[web.1]:     topLevelPackage = _importAndCheckStack(trialname)
2017-01-04T09:10:24.064279+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/twisted/python/reflect.py", line 239, in _importAndCheckStack
2017-01-04T09:10:24.064416+00:00 app[web.1]:     return __import__(importName)
2017-01-04T09:10:24.064417+00:00 app[web.1]:   File "/app/src/taptap/service.py", line 6, in <module>
2017-01-04T09:10:24.064506+00:00 app[web.1]:     from taptap.web import CoreResource
2017-01-04T09:10:24.064507+00:00 app[web.1]:   File "/app/src/taptap/web.py", line 2, in <module>
2017-01-04T09:10:24.064617+00:00 app[web.1]:     import cattr
2017-01-04T09:10:24.064619+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/cattr/__init__.py", line 1, in <module>
2017-01-04T09:10:24.064692+00:00 app[web.1]:     from .converters import Converter
2017-01-04T09:10:24.064693+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/cattr/converters.py", line 23, in <module>
2017-01-04T09:10:24.064797+00:00 app[web.1]:     class Converter(object):
2017-01-04T09:10:24.064799+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/cattr/converters.py", line 180, in Converter
2017-01-04T09:10:24.064946+00:00 app[web.1]:     def _loads_list(self, cl: Type[GenericMeta], obj: Iterable[T]) -> List[T]:
2017-01-04T09:10:24.064947+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/typing.py", line 623, in inner
2017-01-04T09:10:24.065204+00:00 app[web.1]:     return cached(*args, **kwds)
2017-01-04T09:10:24.065205+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/typing.py", line 1062, in __getitem__
2017-01-04T09:10:24.065572+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/typing.py", line 965, in __new__
2017-01-04T09:10:24.065571+00:00 app[web.1]:     orig_bases=self.__orig_bases__)
2017-01-04T09:10:24.066164+00:00 app[web.1]:     self.__tree_hash__ = hash(self._subs_tree()) if origin else hash((self.__name__,))
2017-01-04T09:10:24.066181+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/typing.py", line 1007, in _subs_tree
2017-01-04T09:10:24.066791+00:00 app[web.1]:     tree_args = _subs_tree(self, tvars, args)
2017-01-04T09:10:24.066795+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/typing.py", line 548, in _subs_tree
2017-01-04T09:10:24.067162+00:00 app[web.1]:     tree_args.append(_replace_arg(arg, tvars, args))
2017-01-04T09:10:24.067166+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/typing.py", line 517, in _replace_arg
2017-01-04T09:10:24.067393+00:00 app[web.1]:     return arg._subs_tree(tvars, args)
2017-01-04T09:10:24.067394+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/typing.py", line 1005, in _subs_tree
2017-01-04T09:10:24.067754+00:00 app[web.1]:     if self.__origin__ is None:
2017-01-04T09:10:24.067755+00:00 app[web.1]: AttributeError: 'list' object has no attribute '__origin__'
```

**Comment by Tinche** [comment]
![](http://i2.kym-cdn.com/photos/images/newsfeed/000/406/325/b31.jpg)

Ok, let's see what got changed. :)

**Comment by Tinche** [comment]
Well, the first couple of errors were easy to fix since they were in the type annotations, which I can live without. However, there have been more changes in typing.py, which might actually require API changes. :/

I've filed the first issue here: https://github.com/python/typing/issues/345

**Comment by ilevkivskyi** [comment]
@Tinche 
> first couple of errors were easy to fix since they were in the type annotations, which I can live without

I have filed https://github.com/python/typing/issues/347 for ``Type[GenericMeta]`` failure. Please don't hesitate to file more issues. ``typing`` is still young and I (and probably others too) will be very happy to see more input.

Thank you!

**Comment by Tinche** [comment]
I'm still plugging away at this. Another change is that Union[x, y] is not a class any more, but rather an instance of _Union (if I understand what I'm seeing correctly). So Union[x, y] can't be used with singledispatch directly any more. We can work around this with a separate registry for unions. Unions require special attention anyway.

There are also issues with Tuple[...], I'm digging through singledispatch to work out why.

**Comment by Tinche** [comment]
Hm, interestingly, before:

```
>>> issubclass(typing.Tuple[int], typing.Sequence)
False
```
and currently:
```
>>> issubclass(typing.Tuple[int], typing.Sequence)
True
```
I'd say the current behavior is correct. However this change (I think) makes singledispatch basically choose randomly between `typing.Sequence` and `typing.Tuple` when dispatching on `typing.Tuple[int]`.

**Comment by Tinche** [comment]
Related issue: https://github.com/python/typing/issues/384

**Comment by Tinche** [comment]
Good news! I have cattrs working with the master version of typing.py (with a little help from upstream). Unfortunately, as far as I can tell, this version of typing.py won't be released until 3.5.4 and 3.6.1. typing.py is up on PyPI, but stdlib copies take precedence over pip installed ones, so this doesn't really help. 3.5.2 can make do with v0.2.

What I could do is temporarily bundle a good version of typing.py (as cattr.typing) until the new version is out.

**Comment by Tinche** [comment]
Ok, I'm about ready to cut a new release making us work on 3.6.0. Could you give master a go before I do that?

**Comment by wsanchez** [comment]
@Tinche On my machine with `cattrs==0.2.0` I also see this in Python 3.6.0 but not in Python 3.5.2.

If I switch to master, I no longer get the `__origin__` problem in Python 3.6.0, but I got an infinite recursion error instead.

So I went back to Python  3.5.2 and I noticed that in my `loads` hooks, I've got some assertions that `cl` is the the type that I expected, for example:

```python
def loads_foo(cl: Type, obj: str) -> Foo:
    assert cl is Foo, (cl, obj)
   ...
```

These assertions did not fire in cattrs 0.2.0 but do in master.

(I don't actually use `cl` in these functions, and has just dropped the assertions in to make sure I understood what was going on here and because I'm pedantic.)

It looks like `cl` and `obj` are passed in the opposite order now.  Is that intentional?

To keep moving along, if I swap `cj` and `obj` around, my tests pass… so let's go back to Python  3.6.0 and see what happens…

I'm still hitting an infinite recursion problem… but the traceback runs through my code into the built-in `sqlite3/dbapi2.py` (!!!) where it does `collections.abc.Sequence.register(Row)` and from there is goes into the built-in `typing.py` and then (and here's where you probably care) into `cattr/typing.py`.

So it looks like there's some interaction with `cattr/typing.py` that's blowing up `sqlite3` of all things.  Traceback:

```
[ERROR]
Traceback (most recent call last):
  File "/Users/wsanchez/Developer/MyApplication/.tox/py36-coverage/lib/python3.6/site-packages/twisted/trial/runner.py", line 508, in loadPackage
    module = modinfo.load()
  File "/Users/wsanchez/Developer/MyApplication/.tox/py36-coverage/lib/python3.6/site-packages/twisted/python/modules.py", line 392, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/Users/wsanchez/Developer/MyApplication/.tox/py36-coverage/lib/python3.6/site-packages/twisted/python/reflect.py", line 300, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/Users/wsanchez/Developer/MyApplication/.tox/py36-coverage/lib/python3.6/site-packages/twisted/python/reflect.py", line 239, in _importAndCheckStack
    return __import__(importName)
  File "/Users/wsanchez/Developer/MyApplication/src/myapplication/application/test/test_api.py", line 16, in <module>
    from ...store.sqlite import DataStore
  File "/Users/wsanchez/Developer/MyApplication/src/myapplication/store/sqlite/__init__.py", line 5, in <module>
    from ._store import DataStore
  File "/Users/wsanchez/Developer/MyApplication/src/myapplication/store/sqlite/_store.py", line 17, in <module>
    from ._sqlite import (
  File "/Users/wsanchez/Developer/MyApplication/src/myapplication/store/sqlite/_sqlite.py", line 6, in <module>
    from sqlite3 import (
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sqlite3/dbapi2.py", line 54, in <module>
    collections.abc.Sequence.register(Row)
  File "/Users/wsanchez/Developer/MyApplication/.tox/py36-coverage/bin/../lib/python3.6/abc.py", line 158, in register
    if issubclass(subclass, cls):
  File "/Users/wsanchez/Developer/MyApplication/.tox/py36-coverage/bin/../lib/python3.6/abc.py", line 226, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/Users/wsanchez/Developer/MyApplication/.tox/py36-coverage/bin/../lib/python3.6/abc.py", line 226, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/Users/wsanchez/Developer/MyApplication/.tox/py36-coverage/bin/../lib/python3.6/abc.py", line 207, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 860, in __extrahook__
    if issubclass(subclass, scls):
  File "/Users/wsanchez/Developer/MyApplication/.tox/py36-coverage/lib/python3.6/site-packages/cattr/typing.py", line 1145, in __subclasscheck__
    return super().__subclasscheck__(cls)
  File "/Users/wsanchez/Developer/MyApplication/.tox/py36-coverage/bin/../lib/python3.6/abc.py", line 207, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "/Users/wsanchez/Developer/MyApplication/.tox/py36-coverage/lib/python3.6/site-packages/cattr/typing.py", line 877, in __extrahook__
    if issubclass(subclass, scls):
  File "/Users/wsanchez/Developer/MyApplication/.tox/py36-coverage/bin/../lib/python3.6/abc.py", line 207, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 860, in __extrahook__
    if issubclass(subclass, scls):
  File "/Users/wsanchez/Developer/MyApplication/.tox/py36-coverage/lib/python3.6/site-packages/cattr/typing.py", line 1145, in __subclasscheck__
    return super().__subclasscheck__(cls)
... (continues repeating) …
```

I tried skipping this part of my tests to just the JSON module that's depending on cattrs but that uses hypothesis, which also uses sqlite3, so this is as far as I can go.

**Comment by Tinche** [comment]
So on 3.6.0 and 3.5.3 you're supposed to use `cattr.typing` instead of just `typing`. These versions have a `typing` module that can't be used with cattrs at all, I'm afraid. You're seeing the interplay of the built-in typing and the bundled typing there.

``cattr.loads([1], cattr.typing.List[int])``.

**Comment by glyph** [comment]
Testing on `master` with python 3.6 today, I tried this:

```
from cattr import typing

import attr
import cattr

@attr.s
class B(object):
    c = attr.ib(validator=attr.validators.instance_of(str))

@attr.s
class A(object):
    bs = attr.ib(validator=attr.validators.instance_of(typing.List[B]))

print(cattr.dumps(A([B("hello")])))
print(cattr.loads([{"bs": [{"c": "hello"}]}], typing.List[A]))
```

which resulted in:

```
Traceback (most recent call last):
  File "/Users/glyph/cattrsperiment.py", line 15, in <module>
    print(cattr.dumps(A([B("hello")])))
  File "<attrs generated init a5766281ef1d446e3987eb957aaa035ca52081d2>", line 5, in __init__
  File ".../site-packages/attr/validators.py", line 18, in __call__
    if not isinstance(value, self.type):
  File ".../site-packages/cattr/typing.py", line 1153, in __instancecheck__
    return issubclass(instance.__class__, self)
  File ".../site-packages/cattr/typing.py", line 1139, in __subclasscheck__
    raise TypeError("Parameterized generics cannot be used with class "
TypeError: Parameterized generics cannot be used with class or instance checks
```

Is this supposed to work?

**Comment by Tinche** [comment]
@glyph The short answer is yes, but when we start using metadata instead of picking out types from validators.

The long answer is, `isinstance(x, typing.List[T])` doesn't work any more by design of the `typing` module. So the validator is actually crapping out there. Starting from the next release, I'll switch to using metadata, so this will be possible again. Just can't seem to find the time :/

**Comment by glyph** [comment]
I had to work around this by creating my own little `attrs` front-end (with an explicit note to switch to `cattrs` when these issues are addressed here).  It looks like this:

```
@attr.s
class X(object):
    a = typed(List[whatever])
    b = typed(Y)
```

et cetera.  (`typed` is just a function that returns an `attr.ib` appropriately metadataized).  However, I was a bit surprised by just how _bad_ the `typing` module's API is for getting information about parametric types.  Am I doing it wrong?  Is `__args__` really all I have to go on?

**Comment by ilevkivskyi** [comment]
@glyph 
>  However, I was a bit surprised by just how bad the typing module's API is for getting information about parametric types. Am I doing it wrong? Is __args__ really all I have to go on?

``typing`` has internal API get all imaginable info about generic types and other things like ``Union``: ``__args__``, ``__patameters__``, ``__origin__``, etc. The problem is that these are _private_ and should never be used. If you are interested in public "wrappers" for all these, then vote for https://github.com/python/typing/pull/377 :-)
The plan is to publish this as a separate  package on PyPI and after collecting comments make it part of the stdlib ``typing``.
The proposal is there since January, but Guido was not able to review it for certain reason. If you agree to be a reviewer,  it will speed-up things significantly.
