### ISSUE TITLE
Cattrs 0.9.1 attempts to import lru_cache in python 2.7

### ISSUE THREAD

**Issue by schrockn** [Tinche/cattrs#84]
* cattrs version: 0.9.1
* Python version: 2.7.17
* Operating System: MacOs

### Description

I was testing Airflow in python 2.7 and ran into this bug.

### What I Did

```
(debug-airflow-2.7-04-19-2020) [schrockn@mbp ~/code/dagster (fix-airflow)]$ airflow
Traceback (most recent call last):
  File "/Users/schrockn/venvs/debug-airflow-2.7-04-19-2020/bin/airflow", line 26, in <module>
    from airflow.bin.cli import CLIFactory
  File "/Users/schrockn/venvs/debug-airflow-2.7-04-19-2020/lib/python2.7/site-packages/airflow/bin/cli.py", line 79, in <module>
    api_module = import_module(conf.get('cli', 'api_client'))  # type: Any
  File "/Users/schrockn/.pyenv/versions/2.7.17/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/schrockn/venvs/debug-airflow-2.7-04-19-2020/lib/python2.7/site-packages/airflow/api/client/local_client.py", line 24, in <module>
    from airflow.api.common.experimental import delete_dag
  File "/Users/schrockn/venvs/debug-airflow-2.7-04-19-2020/lib/python2.7/site-packages/airflow/api/common/experimental/delete_dag.py", line 25, in <module>
    from airflow.models.serialized_dag import SerializedDagModel
  File "/Users/schrockn/venvs/debug-airflow-2.7-04-19-2020/lib/python2.7/site-packages/airflow/models/serialized_dag.py", line 32, in <module>
    from airflow.serialization.serialized_objects import SerializedDAG
  File "/Users/schrockn/venvs/debug-airflow-2.7-04-19-2020/lib/python2.7/site-packages/airflow/serialization/serialized_objects.py", line 28, in <module>
    import cattr
  File "/Users/schrockn/venvs/debug-airflow-2.7-04-19-2020/lib/python2.7/site-packages/cattr/__init__.py", line 1, in <module>
    from .converters import Converter, UnstructureStrategy
  File "/Users/schrockn/venvs/debug-airflow-2.7-04-19-2020/lib/python2.7/site-packages/cattr/converters.py", line 15, in <module>
    from ._compat import (
  File "/Users/schrockn/venvs/debug-airflow-2.7-04-19-2020/lib/python2.7/site-packages/cattr/_compat.py", line 2, in <module>
    from functools import lru_cache, singledispatch  # noqa
ImportError: cannot import name lru_cache
```

Tracking in airflow repo here: https://github.com/apache/airflow/issues/8457

**Comment by Tinche** [comment]
Bleh ok. Can you make our upstream upgrade to 1.0, which should be good?

**Comment by schrockn** [comment]
Airflow requires ~=0.9 in their stable revision. https://github.com/apache/airflow/blob/v1-10-stable/setup.py

Not sure why.

**Comment by Tinche** [comment]
Ok, so 0.9.2 would also work I guess?

**Comment by schrockn** [comment]
Yup a quick 0.9.2 release to fix this up would work great

Sent via Superhuman iOS ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by Tinche** [comment]
Should be fixed now in 0.9.2!

**Comment by schrockn** [comment]
confirmed. thanks!

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by timorthi** [comment]
I am using Pipenv and it was unable to find `cattrs==0.9.1` (as defined in my Pipfile.lock) on install because it's now nuked from PyPI in favor of 0.9.2. Not sure if this was intentional, but just a heads up to people experiencing the same issue: You'll have to run `pipenv lock` to have Pipenv's dependency resolver to resolve to 0.9.2.

**Comment by Tinche** [comment]
Unfortunately 0.9.1 was a bad build (uploaded for Python 2, but didn't actually support Python 2), so I choose to nuke it. It wasn't up for very long. Sorry for the inconvenience.
